"""红队工具元数据目录 (第一部分)。

100% 按 dreadnode/ares (https://github.com/dreadnode/ares) 工具签名 1:1 复刻。
"""

from __future__ import annotations
from typing import Any
from .tool_registry import AgentRole, ToolDefinition


def make_tool(name, description, props, required, secret_keys=None):
    schema = {"type": "object", "properties": {f: {"type": t, "description": d} for f, t, d in props}, "required": list(required)}
    return ToolDefinition(name=name, description=description, input_schema=schema, secret_keys=secret_keys or set())


ORCHESTRATOR_TOOLS = []
ORCHESTRATOR_TOOLS.append(make_tool("get_hash_summary", "Get a summary of all collected password hashes across the operation. Returns counts grouped by hash type (NTLM, Kerberos TGS-REP, AS-REP, etc.) and shows how many have been cracked vs remain uncracked.", [], []))
ORCHESTRATOR_TOOLS.append(make_tool("get_credential_summary", "Get a summary of all collected credentials across the operation. Returns counts grouped by domain, distinguishing admin-level credentials from standard user credentials.", [], []))
ORCHESTRATOR_TOOLS.append(make_tool("get_all_hashes", "List all collected password hashes with pagination support. Returns associated usernames, domains, hash types and cracked status. Raw hash material is never returned - dispatch by principal instead.", [("limit", "integer", "Maximum number of hashes to return per page. Defaults to 30."), ("offset", "integer", "Number of hashes to skip for pagination. Defaults to 0.")], []))
ORCHESTRATOR_TOOLS.append(make_tool("get_all_credentials", "List all collected credentials with pagination support. Returns username, domain, whether usable secret material is held, and admin status for each entry. Secret values are never returned.", [("limit", "integer", "Maximum number of credentials to return per page. Defaults to 30."), ("offset", "integer", "Number of credentials to skip for pagination. Defaults to 0.")], []))
ORCHESTRATOR_TOOLS.append(make_tool("get_pending_tasks", "List all pending and in-progress tasks across all agent queues. Returns task IDs, descriptions, assigned roles, current status (pending/running/blocked), and how long each has been in its current state. Use this before dispatching to avoid queueing duplicate work.", [], []))
ORCHESTRATOR_TOOLS.append(make_tool("get_agent_status", "Get the current status of all active agents in the operation. Returns each agent's role, whether it is busy or idle, the task it is currently executing (if any), and the last time it reported activity.", [], []))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_recon", "Dispatch a reconnaissance task to scan a target. The task will be assigned to a recon agent and executed asynchronously.", [("target_ip", "string", "Target IP address to scan"), ("domain", "string", "Target domain (e.g. contoso.local)"), ("techniques", "array", "Specific recon techniques to use (e.g. [nmap, smb_sweep]). Leave empty for general recon.")], ["target_ip"]))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_credential_access", "Dispatch a credential access task (secretsdump, kerberoast, ASREP roast, password spray, etc.) against a target, authenticating as the named principal. Name the principal only - the secret is resolved from operation state at dispatch time. The principal must already appear in get_all_credentials.", [("technique", "string", "Attack technique (e.g. secretsdump, kerberoast, asrep_roast, password_spray, lsassy)"), ("target_ip", "string", "Target IP address"), ("domain", "string", "Domain of the authenticating principal"), ("username", "string", "Username of the authenticating principal"), ("priority", "integer", "Task priority (1=highest, 10=lowest). Default: 5")], ["technique", "target_ip", "domain", "username"], secret_keys={"password", "hash"}))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_lateral_movement", "Dispatch a lateral movement task to move to a new host as the named principal. Techniques include psexec, wmiexec, smbexec, atexec. Name the principal only - the secret is resolved from operation state at dispatch time. Cross-realm combinations are rejected with an explanation.", [("target_ip", "string", "Target host IP to move to"), ("technique", "string", "Lateral movement technique (e.g. psexec, wmiexec, smbexec, atexec)"), ("username", "string", "Username of the authenticating principal"), ("domain", "string", "Domain of the authenticating principal")], ["target_ip", "technique", "username", "domain"]))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_privesc_exploit", "Dispatch an exploitation task for a discovered vulnerability. Provide the vulnerability ID from the discovered vulnerabilities list.", [("vuln_id", "string", "Vulnerability ID to exploit (from discovered vulnerabilities)"), ("priority", "integer", "Task priority (1=highest, 10=lowest). Default: 3")], ["vuln_id"]))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_coercion", "Dispatch a coercion/relay attack against a target. Uses techniques like PetitPotam, PrinterBug to coerce authentication to a relay listener.", [("target_ip", "string", "Target to coerce"), ("listener_ip", "string", "Relay listener IP"), ("techniques", "array", "Coercion techniques (default: [petitpotam, printerbug])")], ["target_ip", "listener_ip"]))
ORCHESTRATOR_TOOLS.append(make_tool("dispatch_crack", "Dispatch a hash cracking task for a principal whose hash is already held in operation state. Name the principal - the hash material is resolved at dispatch time. Check get_all_hashes first; cracking an already-cracked or absent principal is rejected.", [("username", "string", "Username associated with the hash"), ("domain", "string", "Domain associated with the hash"), ("hash_type", "string", "Which held hash type to crack (e.g. ntlm, kerberos_tgs, kerberos_as, mscache2). If omitted, the first uncracked hash for the principal is used.")], ["username", "domain"]))
ORCHESTRATOR_TOOLS.append(make_tool("get_proposed_work", "List work the deterministic automations have proposed and are waiting on you to rule on. Each entry is already validated and executable - the rule that proposed it built the payload. Review these FIRST every turn: approving good work is faster and safer than composing a dispatch yourself. Anything you do not rule on is released automatically when its window expires.", [("limit", "integer", "Maximum proposals to return, lowest priority number first. Defaults to 30.")], []))
ORCHESTRATOR_TOOLS.append(make_tool("approve_work", "Approve proposed work by id, releasing it for dispatch immediately. Pass every id you want to run - approving in bulk is normal and cheap. Ids come from get_proposed_work; an unknown id is reported back rather than ignored.", [("proposal_ids", "array", "Proposal ids to approve (e.g. [p0001, p0002])")], ["proposal_ids"]))
ORCHESTRATOR_TOOLS.append(make_tool("reject_work", "Reject proposed work by id so it is not dispatched and is not re-proposed for a cooldown period. Use this to suppress work that is redundant, aimed at a dead end, or lower value than what you are prioritising. Rejecting is a real decision - the rule that proposed it will stay suppressed, so give a reason you would stand behind.", [("proposal_id", "string", "The proposal id to reject"), ("reason", "string", "Why this work should not run")], ["proposal_id", "reason"]))
ORCHESTRATOR_TOOLS.append(make_tool("complete_operation", "Mark the entire red team operation as complete. This finalizes all outstanding tasks, generates the operation report, and signals all agents to wind down. Should only be called when the operation objectives have been achieved or no further progress is possible. Only the orchestrator may call this; worker roles cannot end the operation.", [("summary", "string", "Final operation summary describing what was accomplished, key findings, compromised assets, and any remaining attack paths not explored.")], ["summary"]))

RECON_TOOLS = []
RECON_TOOLS.append(make_tool("nmap_scan", "Run an nmap scan against target IP(s) or subnet. Returns discovered hosts, open ports, and services.", [("target", "string", "Target IP, hostname, or CIDR range (e.g. 192.168.58.0/24)"), ("ports", "string", "Port specification (e.g. 1-1000, 80,443,445). Use targeted ranges, not all ports."), ("arguments", "string", "Additional nmap arguments (e.g. -sV -sC -O)")], ["target"]))
RECON_TOOLS.append(make_tool("smb_sweep", "Sweep a subnet for hosts with SMB (port 445) open. Returns reachable hosts.", [("targets", "string", "Target IP range or CIDR (e.g. 192.168.58.0/24)")], ["targets"]))
RECON_TOOLS.append(make_tool("enumerate_users", "Enumerate domain users via netexec SMB (--users with --rid-brute fallback). Returns usernames and domain membership.", [("target", "string", "Domain controller IP or hostname"), ("domain", "string", "Target domain name"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("null_session", "boolean", "Use null session (empty creds) for unauthenticated enumeration")], ["target", "domain"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("enumerate_shares", "Enumerate SMB shares on a target host. Returns share names, types, and permissions.", [("target", "string", "Target IP or hostname"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("domain", "string", "Domain name")], ["target"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("smb_signing_check", "Check SMB signing status on target hosts. Identifies relay targets (hosts without signing required).", [("target", "string", "Target IP, hostname, or CIDR range")], ["target"]))
RECON_TOOLS.append(make_tool("run_bloodhound", "Run BloodHound data collection. Requires valid domain credentials.", [("domain", "string", "Target domain"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("dc_ip", "string", "Domain controller IP"), ("collection_method", "string", "Collection method (default: All)")], ["domain", "username", "password", "dc_ip"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("ldap_search", "Execute an LDAP search query against a domain controller. When authenticating with credentials from a different domain (e.g. child domain cred against parent DC), set bind_domain to the credential's domain.", [("target", "string", "DC IP or hostname"), ("domain", "string", "Target domain (used for LDAP base DN)"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("filter", "string", "LDAP filter (e.g. (objectClass=user))"), ("attributes", "string", "Comma-separated attributes to retrieve"), ("bind_domain", "string", "Domain for LDAP bind DN (user@bind_domain). Use when credential domain differs from target domain (e.g. child-domain cred authenticating to parent DC). If omitted, uses domain.")], ["target", "domain", "filter"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("rpcclient_command", "Execute an rpcclient command against a target. Supports pass-the-hash via the hash parameter.", [("target", "string", "Target IP or hostname"), ("command", "string", "rpcclient command (e.g. enumdomusers, enumdomgroups, querygroupmem <rid>)"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("domain", "string", "Domain name"), ("null_session", "boolean", "Use null session (empty anonymous credentials) for unauthenticated SAMR/LSA enumeration"), ("hash", "string", "NTLM hash for pass-the-hash authentication (use instead of password)")], ["target", "command"], secret_keys={"password", "hash"}))
RECON_TOOLS.append(make_tool("dig_query", "Execute a DNS query using dig.", [("query", "string", "DNS query (e.g. contoso.local)"), ("record_type", "string", "Record type (A, SRV, MX, NS, etc.)"), ("server", "string", "DNS server to query")], ["query"]))
RECON_TOOLS.append(make_tool("enumerate_domain_trusts", "Enumerate domain trust relationships via LDAP. Queries trustedDomain objects.", [("target", "string", "DC IP"), ("domain", "string", "Target domain"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("hash", "string", "NTLM hash for pass-the-hash auth (use instead of password)")], ["target", "domain"], secret_keys={"password", "hash"}))
RECON_TOOLS.append(make_tool("check_rdp_reachability", "Check if RDP (port 3389) is reachable on a target host.", [("target", "string", "Target IP or hostname")], ["target"]))
RECON_TOOLS.append(make_tool("check_winrm_reachability", "Check if WinRM (port 5985/5986) is reachable on a target host.", [("target", "string", "Target IP or hostname")], ["target"]))
RECON_TOOLS.append(make_tool("zerologon_check", "Check if a domain controller is vulnerable to Zerologon (CVE-2020-1472).", [("dc_ip", "string", "Domain controller IP address")], ["dc_ip"]))
RECON_TOOLS.append(make_tool("adidnsdump", "Dump AD Integrated DNS records for a domain.", [("dc_ip", "string", "Domain controller IP"), ("domain", "string", "Target domain"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication")], ["dc_ip", "domain", "username", "password"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("save_users_to_file", "Save enumerated domain users to a file for use with other tools.", [("target", "string", "DC IP or hostname"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("domain", "string", "Target domain")], ["target"], secret_keys={"password"}))
RECON_TOOLS.append(make_tool("smbclient_kerberos_shares", "Enumerate SMB shares using Kerberos ticket authentication. Requires a valid TGT in the ccache (no password needed). Use after obtaining a Kerberos ticket via S4U, golden ticket, or ADCS.", [("target", "string", "Target hostname (must match SPN in ticket)"), ("target_ip", "string", "Target IP address (if hostname does not resolve via DNS)")], ["target"]))
RECON_TOOLS.append(make_tool("ldap_acl_enumeration", "Enumerate ACL attack paths by querying nTSecurityDescriptor attributes on AD objects. Identifies dangerous ACEs (GenericAll, WriteDacl, ForceChangePassword, GenericWrite, WriteOwner, Self-Membership) that can be exploited for privilege escalation. Supports pass-the-hash via the hash parameter.", [("target", "string", "DC IP or hostname"), ("domain", "string", "Target domain"), ("username", "string", "Username for authentication"), ("password", "string", "Password for authentication"), ("hash", "string", "NTLM hash for pass-the-hash (use instead of password)"), ("bind_domain", "string", "Domain for LDAP bind DN when credential domain differs from target domain")], ["target", "domain"], secret_keys={"password", "hash"}))

RED_ROLE_TOOLS_PART_A = {AgentRole.ORCHESTRATOR: ORCHESTRATOR_TOOLS, AgentRole.RECON: RECON_TOOLS}