// Minimal markdown viewer backed by `marked` (report.md replay).

import { useMemo } from 'react'
import { marked } from 'marked'

marked.setOptions({ gfm: true, breaks: false })

export function MarkdownView({ markdown }: { markdown: string }) {
  const html = useMemo(() => {
    try {
      return marked.parse(markdown, { async: false }) as string
    } catch {
      return ''
    }
  }, [markdown])

  if (!html) {
    return <pre className="whitespace-pre-wrap text-[11px] text-text-2">{markdown}</pre>
  }
  // Content is generated by our own eval/report.py (trusted, local tool).
  return <div className="md-view" dangerouslySetInnerHTML={{ __html: html }} />
}
