// Minimal markdown viewer backed by `marked` (report.md replay, agent prose,
// docs). className overrides the chrome variant: .md-view (reports),
// .md-inline (terminal thinking streams), .md-doc (GitHub-README style docs).

import { useMemo } from 'react'
import { marked } from 'marked'

marked.setOptions({ gfm: true, breaks: false })

export function MarkdownView({
  markdown,
  className = 'md-view',
}: {
  markdown: string
  className?: string
}) {
  const html = useMemo(() => {
    try {
      return marked.parse(markdown, { async: false }) as string
    } catch {
      return ''
    }
  }, [markdown])

  if (!html) {
    return <pre className="whitespace-pre-wrap text-[11px] text-text-2">{markdown}</pre>
  }
  // Content is generated by our own agents/eval (trusted, local tool).
  return <div className={className} dangerouslySetInnerHTML={{ __html: html }} />
}
